os: linux
  - dist: bionic
  - dist: focal
addons:
  apt:
    packages:
    - libproj-dev
language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
env:
  - PROJ_DISTRO=bionic
  - PROJ_DISTRO=focal
before_install:
  - .travis/${PROJ_DISTRO}-setup.sh
